### ISSUE TITLE
lazy load images?

### ISSUE THREAD

**Issue by andreweick** [aeick/eick#14]

**Comment by budparr** [comment]
going through issues here: I don't think lazy load is appropriate necessarily for what your doing here. Here's an example of where I think it's appropriate: http://www.ndbooks.com/authors/ There are >600 images here and without lazyload the page itself would drag. In my web performance group, lazy loading is a bit frowned upon because images are non-blocking. 

I do notice a drag on page-load, particularly on the home page. We do have a lot of images there, but rather than adding a new script, I'd say we load fewer images, make sure they're optimized, and, I think there's some drag at your server. In my tests, I see Time to First Byte: 3281 ms coming from the media.eick.us subdomain for a 200kb image. So, I think that's a bottleneck, so you might want to put those on a CDN or even use your Github repo to serve the images.

**Comment by budparr** [comment]
keeping open for discussion

**Comment by budparr** [comment]
I also removed a blocking file that I seems to be helping page load performance.

**Comment by andreweick** [comment]
Excellent -- still some weird performance thing (maybe a re-paint event) but much better.

**Comment by budparr** [comment]
It's just that we're loading a lot of images and to give the layout the grid, the javascript isn't loading until all the images are loaded (the grid doesn't work otherwise) - to lazy load on a grid like this I'd have to pre-load a placeholder image for each image, which would mean knowing the size of each one, etc. We can reduce the number of images, but that's the only thing I can think of here.

**Comment by andreweick** [comment]
Roger -- I'll reduce the number of images -- I meant to do that  (this weekend) anyway

**Comment by budparr** [comment]
I changed the number on the home page.
