### ISSUE TITLE
Sluggish

### ISSUE THREAD

**Issue by andreweick** [aeick/eick#24]
The sight still seems to be really really sluggish (over a second to repaint when I adjust size).  Is this because it hasn't been optimized out of debug mode?

**Comment by budparr** [comment]
On every page? Or just the pages with the grid layout? I think the problem is the large images, not the site or code. If it's just on the grid pages, it could because I load the javascript asynchronously, which means the js doesn't even load until have the html and then has to create the grid. If we use JSON/YAML for images we could implement picture element (not compatible with older browsers) to serve smaller images, or, of course, just serve smaller images in the first place. And, just make sure that we're optimizing images that hit the site. Are you cropping and running the images through an optimizer of any sort?

**Comment by budparr** [comment]
You can see in this test that we're getting lightening fast load times (under one second), but the full load time with images is super long: http://www.webpagetest.org/result/150223_9B_16VN/1/details/

**Comment by budparr** [comment]
Two notes about that test. 1) note the letter grades up top. Not sure why the time to first byte is a c because it's quite good, and the "cache static content" is just how Github serves pages. 2) Essentially, not to really draw it out this way, but the green is server, the purples are code, and the blue is content.

**Comment by andreweick** [comment]
Ahh -- must be the imgages -- each image is 200-400K, * 40, is a big number.  I am crop-ing the images, but to a pretty big dimension -- the webpagetest shows some are 400K

i like the idea of using the picture element to serve smaller images, but don't want to keep pilling on changes :-)

**Comment by budparr** [comment]
The picture element is only going to help on smaller devices and I'd bet that your audience is primarily larger devices (other than, perhaps, accessing a particular photo), and then there's extra http requests/polyfills that make it probably not the right solution. 

I'd suggest 
1) cropping your photos judiciously 
2) naming them agnostically (i.e. not specifying an image size specifically so that you can swap in larger files down the road when the browser landscape changes) and 
3) Saving them "for web" AND optimizing them (I use jpeg mini, but a lot of devs use imageoptim because it also runs from the command line).
4) Serving them from a bonafide CDN like cloudfront or rackspace cdn or google cloud storage. GCS doesn't really cache (and in fact is not a CND, but so powerful it doesn't matter), Amazon's Cloudfront (not S3) is widely used. Rackspace's CDN is the easiest to use (they have a gui interface, but I use cyberduck with all of them), but not the cheapest.

**Comment by andreweick** [comment]
Will do -- I was thinking about it in the vault today, but I don't think I'm even HTTP caching those images, so maybe on each repaint is trying to re-download them.

**Comment by andreweick** [comment]
Holy toledo batman!  It seems Safari (my default) is the making it so sluggish -- on chrome it zips along!

Crazy!
