### ISSUE TITLE
photo story layout - full bleed images

### ISSUE THREAD

**Issue by andreweick** [aeick/eick#3]
I know this is moving the goalposts (new SOW?) -- and I *don't* want to derail anything you have in process, *and* I haven't even really seen what you are thinking for me (enough caveats?).  More of a discussion thread...

I had a play with [exposure.co](http://maeick.expsoure.co/mc-lean-all-stars) to share pictures with other soccer parents. -- Although you know I don't like using the 'industrial' sites for things like that, I did like the full-bleed picture.  Would there be a way to have full width pictures in my design?  

I really don't see how to do it with 'just' markdown, and if it isn't 'just' markdown, then gh-pages won't work (not the end of the world, btw -- I probably wouldn't host on github anyway)

The other clever thing was the 'photoset' -- (being able to take 9 pictures and then auto-layout).  It was neat, but I really don't see how to do that without server side logic (doing height and width computing) -- so, well that's hard.

Anyway, back to my thoughts on the ability to "influence layout" of the photos in some kind of deterministic way, but not sure how to approach it without giving up on the ease of the markdown image syntax (and reverting to custom tags)

Anyway, thoughts on a Sunday -- excited about jekyll, starting to think about extensions ...

**Comment by budparr** [comment]
I made a couple of new photo layouts. This is an example of "two_up" http://www.eick.us/family/2014/11/16/all-star-tournament-day-2%20copy/

As you'll see, I put a black background behind the photos. I can remove that, I just wanted to show that you'll want fairly good sized photos in there to fill the space, because otherwise they won't look great. I think this approximates, to some degree, the layout you were talking about, with, again, the limitation being markdown, I think.

I also made something approximating "full bleed" though a true full bleed didn't actually look right, so I gave it a bit of margin, and I think that's effective. Here are examples: http://www.eick.us/family/2014/12/06/jasmine-and-julia/ http://www.eick.us/family/2014/12/19/busy-week/

**Comment by andreweick** [comment]
wow

**Comment by andreweick** [comment]
Really good stuff -- is the "full bleed" image the default behavior?  Do I need to something in the markup to make "full bleed"?

**Comment by budparr** [comment]
```photo_layout: "full"```
I've documented that here: https://github.com/aeick/eick/blob/gh-pages/flags.md

**Comment by andreweick** [comment]
Bud

These are really great -- perfect -- you can go ahead and make the "black band" be the background color and close this.

 really good work
